hack4impact-uiuc/safe-maps

- c2tc-mobile/screens/LiveLocation.js
Creates a button to toggle data layers.
> Toggle layer

- c2tc-mobile/components/PhoneButton.js
- c2tc-mobile/package-lock.json
- c2tc-mobile/package.json
- c2tc-mobile/screens/LiveLocation.js
Implemented a phone button to call a given number.
- [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) for the icons (font awesome pack)
- [react-native-phone-call](https://www.npmjs.com/package/react-native-phone-call) to link to native phone calls
> Implement phone button

- c2tc-mobile/screens/LiveLocation.js
Resolves #37 
Retrieve current location before watching position changes
> Fix initial zoom screen

- .expo/packager-info.json
- .expo/settings.json
- c2tc-mobile/components/NavigationComponents/ButtonInterface.js
- c2tc-mobile/components/NavigationComponents/Navigation.js
- c2tc-mobile/components/NavigationComponents/PhoneButtonInterface.js
> Update button layout in panel

- backend/api/views/emergencyPhone.py
fixed kebab case with phone, same deal as bus stops
> phone kebab fix

- backend/api/views/policeStations.py
> police stations kebab fix

- backend/Dockerfile
> fixing dockerfile for now deployment

- c2tc-mobile/components/Loader.js
- c2tc-mobile/components/NavigationComponents/ButtonInterface.js
- c2tc-mobile/package-lock.json
In [official documentation](https://facebook.github.io/react-native/docs/performance.html#using-consolelog-statements) React-Native states that `console.log` can cause heavy performance issues.
Removed all `console.log` statements and saw improvement in rendering speed for markers. Resolves #73
> Improve marker rendering performance

- c2tc-mobile/screens/LiveLocation.js
> Android initial view fix

- c2tc-mobile/components/NavigationComponents/Navigation.js
- c2tc-mobile/screens/LiveLocation.js
Add `key` to View component to suppress warnings
> Suppress warnings

- backend/api/__init__.py
- backend/api/models/Tips.py
- backend/api/models/User.py
- backend/api/views/main.py
- backend/api/views/tips.py
- backend/api/views/user.py
Created database schema for user and tips
> Created Database Schema for user and tips

- backend/api/models/Tips.py
- backend/api/models/User.py
- backend/api/views/user.py
-endpts for getting all users, getting a single user, creating a new user, updating a user, and deleting a user
-tested with monogdb-compass and postman to ensure database was being updated correctly
> finished user db schema and basic user endpts

- backend/api/models/Tips.py
- backend/api/views/tips.py
- backend/api/views/user.py
- docs/api_docs.md
Added a verify tips put endpoint, and a get all verified tips endpoint
Added a verify user put endpoint because I thought Megha wanted me to but apparently not but whatever
> Verify Tips (+ User) Endpoints

- c2tc-mobile/screens/WelcomeScreen.js
a temporary fix for the welcome page button
> welcome page button fix, kinda works now but needs fixing

- c2tc-mobile/screens/LiveLocation.js
> Fix android loading screen location

- c2tc-mobile/App.js
- c2tc-mobile/components/API.js
- c2tc-mobile/components/NavigationComponents/Tabs.js
- c2tc-mobile/components/Tag.js
- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/constants/Colors.js
- c2tc-mobile/package-lock.json
- c2tc-mobile/screens/LiveLocation.js
- c2tc-mobile/screens/MapScreen.js
- c2tc-mobile/screens/TipDetailsScreen.js
- c2tc-mobile/screens/TipOverviewScreen.js
- c2tc-mobile/screens/WelcomeScreen.js
> Tipoverview

- c2tc-mobile/App.js
- c2tc-mobile/screens/TipForm.js
> Submit tip form - add categories and button

- c2tc-mobile/App.js
- c2tc-mobile/components/API.js
- c2tc-mobile/components/NavigationComponents/Tabs.js
- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/package-lock.json
- c2tc-mobile/package.json
- c2tc-mobile/screens/LiveLocation.js
- c2tc-mobile/screens/TipDetailsScreen.js
- c2tc-mobile/screens/TipOverviewScreen.js
> added api into code

- c2tc-mobile/screens/TipDetailsScreen.js
- c2tc-mobile/screens/TipForm.js
Added back buttons for the Tip Form and for the Tip Detail Screen
> Back Buttons Added

- c2tc-mobile/package-lock.json
- c2tc-mobile/screens/LiveLocation.js
> Geolocation address conversion

- c2tc-mobile/App.js
- c2tc-mobile/components/API.js
- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/screens/LoginScreen.js
- c2tc-mobile/screens/ProfileScreen.js
- c2tc-mobile/screens/RegistrationScreen.js
- c2tc-mobile/screens/TipOverviewScreen.js
- c2tc-mobile/yarn.lock
> Implement login and registration pages

- backend/Pipfile
- backend/api/views/tips.py
- backend/manage.py
- c2tc-mobile/components/API.js
- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/screens/TipOverviewScreen.js
Endpoint and function call for getting all tips within 0.1 miles of a latitude and longitude.
Endpoint and function call for getting all unverified/pending tips
> Pending Tips and Tips Nearby Endpoints

- c2tc-mobile/screens/LiveLocation.js
> Fix center location bug

- c2tc-mobile/screens/LiveLocation.js
Fix location centering and initial loading
> Fix init location fix

- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/constants/Colors.js
- c2tc-mobile/screens/EditProfileScreen.js
- c2tc-mobile/screens/IntroScreen.js
- c2tc-mobile/screens/NotificationScreen.js
- c2tc-mobile/screens/ProfileScreen.js
- c2tc-mobile/screens/SettingsScreen.js
- c2tc-mobile/screens/TipCategories.js
- c2tc-mobile/screens/TipForm.js
- c2tc-mobile/screens/TipOverviewScreen.js
- c2tc-mobile/screens/WelcomeScreen.js
fixed profile screen link to settings page and rerouted some pages
> Fix profile

- c2tc-mobile/screens/ProfileScreen.js
- c2tc-mobile/screens/SettingsScreen.js
- c2tc-mobile/screens/TipOverviewScreen.js
> Conditional Background Image

- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/package-lock.json
- c2tc-mobile/screens/TipOverviewScreen.js
- ran `yarn run format`
- updated the style of tips page
> updated the style

- c2tc-mobile/components/Geocoding.js
- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/screens/TipForm.js
- c2tc-mobile/screens/TipOverviewScreen.js
Small changes to the tip screen
> Small Fixes to Tip Overview Page

- c2tc-mobile/components/Geocoding.js
- c2tc-mobile/components/TipOverview.js
- c2tc-mobile/screens/TipForm.js
> Displays Addresses from Latitude Longitude

- auth_server/src/api/register.js
- auth_server/src/utils/pinHelpers.js
- c2tc-mobile/yarn.lock
> fixed auth bug

- c2tc-mobile/App.js
- c2tc-mobile/components/TipOverview.js
> fixed nav bug

- c2tc-mobile/components/API.js
- c2tc-mobile/screens/TipOverviewScreen.js
> Fixed upvote requet bug

- backend/api/core.py
- backend/api/views/auth.py
- backend/api/views/tips.py
- backend/api/views/user.py
- c2tc-mobile/components/API.js
- c2tc-mobile/screens/EditProfileScreen.js
- c2tc-mobile/screens/ProfileScreen.js
- c2tc-mobile/screens/TipDetailsScreen.js
- c2tc-mobile/screens/VerificationScreen.js
- c2tc-mobile/yarn.lock
Convert backend and API.js to use tokens instead of user_id
> Use tokens

- backend/api/models/User.py
- backend/api/views/auth.py
- backend/api/views/user.py
> added in trusted field to User model

- c2tc-mobile/screens/VerificationScreen.js
> Fixed bug when determing success of POST /verifyEmail

- backend/api/views/tips.py
> fix backend bug

- backend/api/models/User.py
- backend/api/views/auth.py
> Added in email property to User model

- c2tc-mobile/screens/SettingsScreen.js
Clears the async storage of the verifiedPin and token values. Does not invalidate the current token used by the user. Logout button is on the upper right of the setttings screen.
> Logout Button

- c2tc-mobile/App.js
changed App.js shouldNotify function to return notifications after being filtered by user notification settings
> added notification filtering functionality to app

- c2tc-mobile/screens/NotificationScreen.js
- c2tc-mobile/screens/ProfileScreen.js
- c2tc-mobile/screens/TipDetailsScreen.js
- c2tc-mobile/screens/TipOverviewScreen.js
Components updated:
- ProfileScreen
> Use promise all in component did/will mount functions
